### ISSUE TITLE
Dashboard Page

### ISSUE THREAD

**Issue by adamwitko** [adamwitkotest/Stories#4]
# Story

**In order to** enter the portal   
**As a** user  
**I want** to provide my login credentials on a web page  

## Scenarios

**Given** a user  
**When** they visit `/login`  
**Then** the user can login to the portal  

## Acceptance criteria

-  Login page contains username and password fields
-  On valid login the user is redirected to the portal

## Tasks

- [x] Create empty page adamwitkotest/something#3
- [x] Style page adamwitkotest/something#4
- [ ] Get user details

## Notes

Don't worry about styling the page yet.
